[package]
name = "synpixel/png"
description = "Fork of MaximumADHD's Roblox-PNG-Library modified for Wally"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = ["MaximumADHD"]

[dependencies]
